### ISSUE TITLE
Mixin failure on 1.17 (21w19a)

### ISSUE THREAD

**Issue by Leo40Git** [SuperCoder7979/databreaker#8]
```
[main/FATAL] (mixin) Mixin apply failed databreaker.mixins.json:fix_log_spam.MixinLevelStorageClient -> net.minecraft.world.level.storage.LevelStorage:
org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException
PRIVATE @Overwrite method createLevelDataParser in databreaker.mixins.json:fix_log_spam.MixinLevelStorageClient cannot reduce visibiliy of PUBLIC target method
```
Seems like method visibility got changed here.

(also I just noticed the error misspelled "visibility" lol)

**Comment by Leo40Git** [comment]
Fixed by c0166ee9990b98191f80058e11ce17fe25278da4.

**Comment by Ristovski** [comment]
@Leo40Git This broke Jitpack builds with `> You are using an outdated version of Java (8). Java 16 or higher is required.`
https://jitpack.io/com/github/SuperCoder7979/databreaker/0.2.7/build.log

**Comment by Leo40Git** [comment]
That's another issue, a `jitpack.yaml` file needs to be added.

**Comment by Ristovski** [comment]
Whoops, didn't notice you weren't the one who pushed that commit. My bad.
